"""
Alert Data Models
=================
Pydantic models for safety alerts.

Alerts are triggered when AI detects risky swimmer behavior.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class AlertType(str, Enum):
    """
    Types of alerts that can be triggered
    """
    STATIONARY = "stationary"          # Swimmer not moving for extended time
    ERRATIC = "erratic"                # Erratic movement pattern
    ZONE_VIOLATION = "zone_violation"  # Swimmer entered restricted area
    DROWNING = "drowning"              # Possible drowning detected (future)


class AlertSeverity(str, Enum):
    """
    Alert severity levels
    """
    LOW = "low"           # Informational
    MEDIUM = "medium"     # Caution
    HIGH = "high"         # Immediate attention
    CRITICAL = "critical" # Emergency response required


class AlertStatus(str, Enum):
    """
    Alert lifecycle status
    """
    ACTIVE = "active"              # Alert just triggered
    ACKNOWLEDGED = "acknowledged"  # Lifeguard has seen it
    RESOLVED = "resolved"          # Situation resolved
    FALSE_POSITIVE = "false_positive"  # Not a real danger


class AlertBase(BaseModel):
    """Base alert data"""
    camera_id: str = Field(..., description="Camera that detected the alert")
    track_id: int = Field(..., description="Swimmer track ID")
    alert_type: AlertType
    severity: AlertSeverity
    risk_score: float = Field(..., ge=0, le=100, description="Risk score (0-100)")


class AlertCreate(AlertBase):
    """
    Data required to create a new alert
    
    Generated by risk_engine in AI pipeline.
    """
    snapshot_url: Optional[str] = Field(None, description="Path to alert snapshot image")


class AlertUpdate(BaseModel):
    """
    Data for updating an existing alert
    
    Used when lifeguard acknowledges or resolves alert.
    """
    status: Optional[AlertStatus] = None
    acknowledged_by: Optional[str] = Field(None, description="Who acknowledged the alert")
    notes: Optional[str] = Field(None, description="Lifeguard notes")


class AlertInDB(AlertBase):
    """
    Complete alert record as stored in MongoDB
    """
    alert_id: str = Field(..., description="Unique alert identifier")
    timestamp: datetime = Field(..., description="When alert was triggered")
    snapshot_url: Optional[str] = None
    status: AlertStatus = Field(default=AlertStatus.ACTIVE)
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    notes: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        from_attributes = True


class AlertResponse(AlertInDB):
    """
    Alert data returned by API
    """
    pass


class AlertsListResponse(BaseModel):
    """
    API response for list of alerts
    """
    success: bool = True
    data: list[AlertResponse]
    count: int
    message: Optional[str] = None

