"""
Swimmer Data Models
===================
Pydantic models for swimmer tracking data.

Why Pydantic?
- Automatic data validation
- Type checking at runtime
- JSON serialization/deserialization
- Clear API documentation (auto-generated by FastAPI)
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class BoundingBox(BaseModel):
    """
    Bounding box coordinates for a detected swimmer
    
    Coordinates are in pixels (x, y) from top-left corner of frame.
    """
    x1: int = Field(..., description="Top-left X coordinate")
    y1: int = Field(..., description="Top-left Y coordinate")
    x2: int = Field(..., description="Bottom-right X coordinate")
    y2: int = Field(..., description="Bottom-right Y coordinate")


class SwimmerBase(BaseModel):
    """Base swimmer data (shared fields)"""
    camera_id: str = Field(..., description="Camera identifier")
    track_id: int = Field(..., description="Unique track ID from AI pipeline")
    bbox: BoundingBox = Field(..., description="Bounding box coordinates")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0-1)")


class SwimmerCreate(SwimmerBase):
    """
    Data required to create a new swimmer record
    
    Used when receiving data from AI pipeline.
    """
    pass


class SwimmerUpdate(BaseModel):
    """
    Data for updating an existing swimmer record
    
    All fields are optional (partial update).
    """
    bbox: Optional[BoundingBox] = None
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    last_seen: Optional[datetime] = None
    status: Optional[str] = Field(None, pattern="^(active|inactive|alerted)$")


class SwimmerInDB(SwimmerBase):
    """
    Complete swimmer record as stored in MongoDB
    
    Includes all tracking metadata.
    """
    first_seen: datetime = Field(..., description="First detection timestamp")
    last_seen: datetime = Field(..., description="Last detection timestamp")
    status: str = Field(default="active", description="Current status: active, inactive, alerted")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        """Pydantic configuration"""
        from_attributes = True  # Allow ORM-style attribute access


class SwimmerResponse(SwimmerInDB):
    """
    Swimmer data returned by API endpoints
    
    Same as SwimmerInDB, formatted for JSON response.
    """
    pass


class SwimmersListResponse(BaseModel):
    """
    API response for list of swimmers
    
    Standardized response format with metadata.
    """
    success: bool = True
    data: list[SwimmerResponse]
    count: int
    message: Optional[str] = None


